export default {
  // Color
  PRIMARY_COLOR: '#295382',
  SECONDARY_COLOR: '#52676D',
  LABEL_COLOR: '#494955',
  LABEL_BG_COLOR: '#EBEBEB',
  AVAILABLE_COLOR: '#ACCD00',
  UNAVAILABLE_COLOR: '#FBC02D',
  BACKGROUND_COLOR: '#F5F5F5',
  SURFACE_COLOR: '#FFFFFF',
  PRIMARY_TEXT_COLOR: '#1C1C1E',
  SECONDARY_TEXT_COLOR: '#6C6C6C',
  ON_PRIMARY_COLOR: '#FFFFFF',
};
